import type {
  Property,
  Room,
  FloorPlan,
  PlanHotspot,
  Customer,
  Booking,
  Review,
} from "@/db/schema";

export const px = (id: number) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1600`;

export type PropertyData = Property;
export type RoomData = Room;
export type FloorPlanData = FloorPlan;
export type HotspotData = PlanHotspot;
export type CustomerData = Customer;
export type BookingData = Booking;
export type ReviewData = Review;

export const DEMO_PROPERTIES: PropertyData[] = [
  {
    id: 1,
    title: "The Meridian Courtyard",
    slug: "meridian-courtyard-mumbai",
    tagline: "Lantern-lit courtyards in the heart of Bandra",
    description:
      "A 12-suite boutique stay wrapped around a reflecting pool. Every room is captured in 360°, so guests walk the courtyard, living suite, and bath before they book. Hosts pin those same views onto the uploaded floor plan.",
    type: "hotel",
    listingType: "rent",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    address: "14 Chapel Road, Bandra West, Mumbai",
    price: 8900,
    bedrooms: 1,
    bathrooms: 1,
    maxGuests: 3,
    areaSqft: 680,
    rating: 4.92,
    reviewCount: 186,
    coverImage: px(33951871),
    images: [px(33951871), px(3011575), px(32334231), px(2725675), px(8082221)],
    amenities: ["Pool", "Breakfast", "Airport pickup", "Workspace", "360° tour", "Concierge"],
    hostName: "Ananya Kapoor",
    hostRole: "Hotelier",
    featured: true,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: 2,
    title: "Palm Grove Villa",
    slug: "palm-grove-villa-goa",
    tagline: "Private pool villa under coconut canopy",
    description:
      "A four-bedroom tropical villa with a sunken living room opening onto the pool deck. Walk the plan, tap a View pin, and spin through each room in 360° — the same flow a guest would take from the gate to the master suite.",
    type: "villa",
    listingType: "rent",
    city: "Goa",
    state: "Goa",
    country: "India",
    address: "Aguada Road, Candolim, Goa",
    price: 18500,
    bedrooms: 4,
    bathrooms: 4,
    maxGuests: 10,
    areaSqft: 4200,
    rating: 4.88,
    reviewCount: 94,
    coverImage: px(6875530),
    images: [px(6875530), px(6875519), px(36965360), px(28054852), px(7214450)],
    amenities: ["Private pool", "Chef on request", "Beach 8 min", "Garden", "Parking", "360° tour"],
    hostName: "Rafael D'Souza",
    hostRole: "Villa host",
    featured: true,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: 3,
    title: "Skyline Residences",
    slug: "skyline-residences-bangalore",
    tagline: "A quiet penthouse above Indiranagar",
    description:
      "Floor-to-ceiling glass, a study nook, and a kitchen meant for long dinners. The uploaded apartment plan has View buttons on living, bedroom, kitchen and bath — each opening a true 360° capture.",
    type: "apartment",
    listingType: "rent",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    address: "12th Main, Indiranagar, Bengaluru",
    price: 4200,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 4,
    areaSqft: 1450,
    rating: 4.81,
    reviewCount: 128,
    coverImage: px(7045915),
    images: [px(7045915), px(30554297), px(6077368), px(7045303), px(7533852)],
    amenities: ["City view", "Kitchen", "Fast wifi", "Washer", "Workspace", "360° tour"],
    hostName: "Meera Iyer",
    hostRole: "Superhost",
    featured: true,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: 4,
    title: "Suryagarh Heritage Estate",
    slug: "suryagarh-heritage-estate",
    tagline: "Sandstone plots with courtyard villas for sale",
    description:
      "A gated heritage estate outside Jaisalmer. Buyers inspect the site plan, tap any villa footprint, and stand inside the courtyard or living hall in 360° — no site visit required to shortlist a plot.",
    type: "plot",
    listingType: "sale",
    city: "Jaisalmer",
    state: "Rajasthan",
    country: "India",
    address: "Sam Road, Jaisalmer",
    price: 8500000,
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 8,
    areaSqft: 5400,
    rating: 4.97,
    reviewCount: 41,
    coverImage: px(33726143),
    images: [px(33726143), px(33681488), px(33726144), px(33726141)],
    amenities: ["Gated estate", "Clubhouse", "Lake view plots", "Title clear", "Site plan", "360° walkthrough"],
    hostName: "House of Rathore",
    hostRole: "Developer",
    featured: true,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: 5,
    title: "Mistwood Lodge",
    slug: "mistwood-lodge-manali",
    tagline: "Cedar cabin above the Beas valley",
    description:
      "A two-bedroom cedar lodge with a wood stove and a wraparound deck. The floor plan pins open 360° captures of the living hall, loft bedroom and bath — useful when snow keeps guests from touring in person.",
    type: "cottage",
    listingType: "rent",
    city: "Manali",
    state: "Himachal Pradesh",
    country: "India",
    address: "Old Manali Road, Manali",
    price: 6700,
    bedrooms: 2,
    bathrooms: 2,
    maxGuests: 5,
    areaSqft: 1180,
    rating: 4.86,
    reviewCount: 77,
    coverImage: px(17832881),
    images: [px(17832881), px(5897389), px(13633304), px(7746548)],
    amenities: ["Fireplace", "Mountain view", "Kitchen", "Parking", "Heating", "360° tour"],
    hostName: "Kabir Thakur",
    hostRole: "Lodge host",
    featured: false,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: 6,
    title: "Naini Edge Cottage",
    slug: "naini-edge-cottage",
    tagline: "A timber house on the lake’s quieter shore",
    description:
      "Wake to mist on Naini Lake. The uploaded plan maps the deck, living room and bedroom; each View pin drops you into a 360° interior so the light and lake alignment are obvious before you book.",
    type: "cottage",
    listingType: "rent",
    city: "Nainital",
    state: "Uttarakhand",
    country: "India",
    address: "Mallital, Nainital",
    price: 5400,
    bedrooms: 2,
    bathrooms: 1,
    maxGuests: 4,
    areaSqft: 980,
    rating: 4.79,
    reviewCount: 63,
    coverImage: px(26599273),
    images: [px(26599273), px(20079776), px(5016527), px(2725675)],
    amenities: ["Lake view", "Deck", "Kitchen", "Fireplace", "Kayak", "360° tour"],
    hostName: "Sana Bisht",
    hostRole: "Host",
    featured: false,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: 7,
    title: "Indigo House Loft",
    slug: "indigo-house-loft-delhi",
    tagline: "A warehouse loft in Shahpur Jat",
    description:
      "Double-height living, a chef’s kitchen, and a sleeping loft. The plan is pinned with View buttons so remote guests can stand in the kitchen island and spin toward the mezzanine.",
    type: "apartment",
    listingType: "rent",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    address: "Shahpur Jat, New Delhi",
    price: 5100,
    bedrooms: 1,
    bathrooms: 2,
    maxGuests: 3,
    areaSqft: 1320,
    rating: 4.74,
    reviewCount: 52,
    coverImage: px(6077368),
    images: [px(6077368), px(7045303), px(8082197), px(7533852)],
    amenities: ["Loft", "Designer kitchen", "Workspace", "Fast wifi", "Washer", "360° tour"],
    hostName: "Dev Malhotra",
    hostRole: "Designer-host",
    featured: false,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: 8,
    title: "Backwater View Plots",
    slug: "backwater-view-plots",
    tagline: "Waterside parcels with villa footprints",
    description:
      "Eight freehold plots along a quiet backwater. The selling plot map is uploaded by the developer; each villa pad has a View button that opens a 360° sample interior and jetty outlook.",
    type: "plot",
    listingType: "sale",
    city: "Alleppey",
    state: "Kerala",
    country: "India",
    address: "Punnamada, Alappuzha",
    price: 4200000,
    bedrooms: 3,
    bathrooms: 3,
    maxGuests: 6,
    areaSqft: 3200,
    rating: 4.83,
    reviewCount: 19,
    coverImage: px(16588337),
    images: [px(16588337), px(36422828), px(5016527), px(6875531)],
    amenities: ["Water frontage", "Clear title", "Road access", "Club jetty", "Site plan", "360° walkthrough"],
    hostName: "Malabar Estates",
    hostRole: "Developer",
    featured: false,
    status: "active",
    createdAt: new Date(),
  },
];

export const DEMO_ROOMS: RoomData[] = [
  { id: 1, propertyId: 1, name: "Courtyard lobby", description: "Lanterns, water, and the arrival hall.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(33951871), sortOrder: 0 },
  { id: 2, propertyId: 1, name: "Living suite", description: "Evening light on the sitting room.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(3011575), sortOrder: 1 },
  { id: 3, propertyId: 1, name: "Bedroom", description: "King suite with linen and warm lamps.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(32334231), sortOrder: 2 },
  { id: 4, propertyId: 1, name: "Marble bath", description: "Freestanding tub and brass fittings.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(2725675), sortOrder: 3 },
  { id: 5, propertyId: 2, name: "Living pavilion", description: "Open living onto the pool deck.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(6875530), sortOrder: 0 },
  { id: 6, propertyId: 2, name: "Master bedroom", description: "Pool-facing master with linen drapes.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(6875519), sortOrder: 1 },
  { id: 7, propertyId: 2, name: "Kitchen", description: "Chef’s kitchen for long Goan lunches.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(36965360), sortOrder: 2 },
  { id: 8, propertyId: 2, name: "Bath", description: "Indoor-outdoor marble bath.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(28054852), sortOrder: 3 },
  { id: 9, propertyId: 3, name: "Living", description: "City lights through the glass wall.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(7045915), sortOrder: 0 },
  { id: 10, propertyId: 3, name: "Bedroom", description: "Quiet bedroom off the foyer.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(30554297), sortOrder: 1 },
  { id: 11, propertyId: 4, name: "Courtyard villa", description: "Sandstone courtyard of Villa A.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(33726143), sortOrder: 0 },
  { id: 12, propertyId: 5, name: "Living hall", description: "Cedar hall with the wood stove.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(17832881), sortOrder: 0 },
  { id: 13, propertyId: 6, name: "Lake living", description: "Living room aligned to the water.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(26599273), sortOrder: 0 },
  { id: 14, propertyId: 7, name: "Loft living", description: "Double-height living with city glass.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(6077368), sortOrder: 0 },
  { id: 15, propertyId: 8, name: "Villa pad interior", description: "Sample villa living for plot buyers.", panoramaUrl: "https://photo-sphere-viewer-data.netlify.app/assets/sphere.jpg", thumbnailUrl: px(16588337), sortOrder: 0 },
];

export const DEMO_FLOOR_PLANS: FloorPlanData[] = [
  { id: 1, propertyId: 1, name: "Suite plan — Level 1", imageUrl: px(32334231), description: "Tap a View pin to stand inside that room." },
  { id: 2, propertyId: 2, name: "Villa plan", imageUrl: px(28054852), description: "Pool deck, living pavilion, and bedrooms." },
  { id: 3, propertyId: 3, name: "Apartment plan", imageUrl: px(30554297), description: "Foyer to glass living wall." },
  { id: 4, propertyId: 4, name: "Estate plot map", imageUrl: px(33681488), description: "Villa footprints and clubhouse on the selling map." },
  { id: 5, propertyId: 5, name: "Lodge plan", imageUrl: px(13633304), description: "Hall, loft, and bath." },
  { id: 6, propertyId: 6, name: "Cottage plan", imageUrl: px(20079776), description: "Deck-aligned living and bedroom." },
  { id: 7, propertyId: 7, name: "Loft plan", imageUrl: px(7045303), description: "Kitchen island under the sleeping loft." },
  { id: 8, propertyId: 8, name: "Selling plot map", imageUrl: px(36422828), description: "Each pad opens a 360° sample interior." },
];

export const DEMO_HOTSPOTS: HotspotData[] = [
  { id: 1, floorPlanId: 1, roomId: 1, label: "Lobby", xPercent: 18, yPercent: 42 },
  { id: 2, floorPlanId: 1, roomId: 2, label: "Living", xPercent: 46, yPercent: 38 },
  { id: 3, floorPlanId: 1, roomId: 3, label: "Bedroom", xPercent: 72, yPercent: 34 },
  { id: 4, floorPlanId: 1, roomId: 4, label: "Bath", xPercent: 78, yPercent: 62 },
  { id: 5, floorPlanId: 2, roomId: 5, label: "Living", xPercent: 40, yPercent: 46 },
  { id: 6, floorPlanId: 2, roomId: 6, label: "Master", xPercent: 68, yPercent: 30 },
  { id: 7, floorPlanId: 2, roomId: 7, label: "Kitchen", xPercent: 28, yPercent: 62 },
  { id: 8, floorPlanId: 2, roomId: 8, label: "Bath", xPercent: 74, yPercent: 58 },
  { id: 9, floorPlanId: 3, roomId: 9, label: "Living", xPercent: 48, yPercent: 40 },
  { id: 10, floorPlanId: 3, roomId: 10, label: "Bedroom", xPercent: 72, yPercent: 32 },
  { id: 11, floorPlanId: 4, roomId: 11, label: "Villa A", xPercent: 32, yPercent: 38 },
  { id: 12, floorPlanId: 5, roomId: 12, label: "Hall", xPercent: 42, yPercent: 44 },
  { id: 13, floorPlanId: 6, roomId: 13, label: "Living", xPercent: 44, yPercent: 42 },
  { id: 14, floorPlanId: 7, roomId: 14, label: "Living", xPercent: 46, yPercent: 40 },
  { id: 15, floorPlanId: 8, roomId: 15, label: "Plot 3", xPercent: 36, yPercent: 40 },
];

export const DEMO_CUSTOMERS: CustomerData[] = [
  { id: 1, name: "Priya Sharma", email: "priya.sharma@email.com", phone: "+91 98200 11420", type: "guest", status: "booked", city: "Mumbai", notes: "Prefers courtyard-facing suites. Repeat guest.", totalSpent: 26700, createdAt: new Date() },
  { id: 2, name: "Arjun Mehta", email: "arjun.mehta@email.com", phone: "+91 98111 33410", type: "buyer", status: "lead", city: "Delhi", notes: "Interested in Villa A at Suryagarh. Wants 360 walkthrough of courtyard.", totalSpent: 0, createdAt: new Date() },
  { id: 3, name: "Leah Fernandes", email: "leah.f@email.com", phone: "+91 98812 77621", type: "guest", status: "booked", city: "Goa", notes: "Family of 6. Requested chef for Saturday.", totalSpent: 55500, createdAt: new Date() },
  { id: 4, name: "Vikram Rao", email: "vikram.rao@email.com", phone: "+91 98450 22109", type: "guest", status: "active", city: "Bangalore", notes: "Works remotely. Needs desk and fast wifi.", totalSpent: 12600, createdAt: new Date() },
  { id: 5, name: "Nandini Joshi", email: "nandini.j@email.com", phone: "+91 94220 88014", type: "inquiry", status: "lead", city: "Pune", notes: "Asked for Alleppey plot sizes and title papers.", totalSpent: 0, createdAt: new Date() },
  { id: 6, name: "Omar Qureshi", email: "omar.q@email.com", phone: "+91 99001 45032", type: "guest", status: "completed", city: "Hyderabad", notes: "Loved the Manali lodge. Left a 5-star review.", totalSpent: 20100, createdAt: new Date() },
  { id: 7, name: "Sara Iqbal", email: "sara.iqbal@email.com", phone: "+91 98180 66721", type: "buyer", status: "active", city: "Jaipur", notes: "Second site visit scheduled after 360 tour.", totalSpent: 0, createdAt: new Date() },
  { id: 8, name: "Rohan Desai", email: "rohan.desai@email.com", phone: "+91 98700 19283", type: "guest", status: "booked", city: "Ahmedabad", notes: "Anniversary stay. Late checkout requested.", totalSpent: 17800, createdAt: new Date() },
];

export const DEMO_BOOKINGS: BookingData[] = [
  { id: 1, propertyId: 1, customerId: 1, guestName: "Priya Sharma", guestEmail: "priya.sharma@email.com", guestPhone: "+91 98200 11420", checkIn: "2026-04-12", checkOut: "2026-04-15", guests: 2, nights: 3, totalAmount: 26700, status: "confirmed", listingType: "rent", createdAt: new Date() },
  { id: 2, propertyId: 2, customerId: 3, guestName: "Leah Fernandes", guestEmail: "leah.f@email.com", guestPhone: "+91 98812 77621", checkIn: "2026-04-18", checkOut: "2026-04-21", guests: 6, nights: 3, totalAmount: 55500, status: "confirmed", listingType: "rent", createdAt: new Date() },
  { id: 3, propertyId: 3, customerId: 4, guestName: "Vikram Rao", guestEmail: "vikram.rao@email.com", guestPhone: "+91 98450 22109", checkIn: "2026-03-28", checkOut: "2026-03-31", guests: 1, nights: 3, totalAmount: 12600, status: "completed", listingType: "rent", createdAt: new Date() },
  { id: 4, propertyId: 5, customerId: 6, guestName: "Omar Qureshi", guestEmail: "omar.q@email.com", guestPhone: "+91 99001 45032", checkIn: "2026-02-10", checkOut: "2026-02-13", guests: 3, nights: 3, totalAmount: 20100, status: "completed", listingType: "rent", createdAt: new Date() },
  { id: 5, propertyId: 6, customerId: 8, guestName: "Rohan Desai", guestEmail: "rohan.desai@email.com", guestPhone: "+91 98700 19283", checkIn: "2026-04-22", checkOut: "2026-04-25", guests: 2, nights: 3, totalAmount: 16200, status: "pending", listingType: "rent", createdAt: new Date() },
  { id: 6, propertyId: 4, customerId: 2, guestName: "Arjun Mehta", guestEmail: "arjun.mehta@email.com", guestPhone: "+91 98111 33410", checkIn: "2026-04-08", checkOut: "2026-04-08", guests: 2, nights: 1, totalAmount: 0, status: "pending", listingType: "sale", createdAt: new Date() },
];

export const DEMO_REVIEWS: ReviewData[] = [
  { id: 1, propertyId: 1, author: "Priya Sharma", rating: 5, comment: "The 360 tour of the courtyard sold me. The suite looked exactly like the plan pins promised.", createdAt: new Date() },
  { id: 2, propertyId: 1, author: "Kabir Lal", rating: 5, comment: "Quiet, lantern-lit, and the bath is a dream. Staff left fruit after a late arrival.", createdAt: new Date() },
  { id: 3, propertyId: 2, author: "Leah Fernandes", rating: 5, comment: "Kids lived in the pool. Being able to spin through every room on the plan made the family yes easy.", createdAt: new Date() },
  { id: 4, propertyId: 3, author: "Vikram Rao", rating: 4, comment: "Desk, light, and a kitchen that actually works. Slight street noise after 11.", createdAt: new Date() },
  { id: 5, propertyId: 5, author: "Omar Qureshi", rating: 5, comment: "Woke to snow on the cedar roof. The loft 360 was accurate — bring wool socks.", createdAt: new Date() },
];
